

## defer

defer 是 Golang 流程控制的一个关键字，用于将一个函数调用推送到一个链表中，等其外围函数返回后调用，常用于简化各种清理工作，如：

```go
func testDefer() {
    defer fmt.Println("do defer")
    fmt.Println("do testDefer")
}

$ go run main.go
do testDefer
do defer
```

### 调用顺序

如果又多个 `defer`, 那么其调用顺序类似于 **栈**，后声明的会先调用：

```go
func testDefer() {
    for i := 0; i < 3; i ++ {
        defer fmt.Println(i)
    }
    fmt.Println("end")
}

$ go run main.go
end
2
1
0
```

原因在于 `defer` 在实现上是一个链表，每个延时调用都会被转换成一个 `runtime._defer` 节点, 每次创建一个新节点后，这个新节点会被放在链表的首部，外部函数返回后，会按链表从前往后遍历执行延时函数。

```go
type _defer struct {
    // ...
	fn        *funcval // 被延时调用的函数
	link      *_defer
}

func newdefer(siz int32) *_defer {
	var d *_defer
	gp := getg()
    // 创建新的 _defer (d) ...
	d.link = gp._defer
	gp._defer = d
	return d
}
```

需要注意的是 `return d` 并不是一个原子操作，它是先赋值，再返回，而执行 `_defer` 链表其实是发生在返回赋值之后：

```go
func testDefer() int {
    var a int
    defer func() {
        a ++
    }()
    return a
}

func main() {
    fmt.Println(testDefer())
}

$ go run main.go
0
```

上面的代码可以理解为：

```go
func testDefer() (temp int) {
    var a int
    defer func() {
        a ++
    }()
    temp = a
    return temp
}
```

这也是 defer 可以读取到具名返回值的原因，如：

```go
func main() {
    res := func()(res int){
        defer func(){
            res ++
        }()
        return 1
    }()
    fmt.Println(res)
}

$ go run main.go
2
```



### 预计算参数

执行下面的代码, 期望结果为 1， 但实际输出 0， 原因在于当函数执行到 `defer` 时，编译器会拷贝延迟函数用到的外部变量，而此时 `ab` 都是初始值 0，为了解决这个问题，我们可以使用匿名函数：

```go
func testDefer() {
    var a, b int
    defer fmt.Println(a - b)
    a, b = 10, 9
}

$ go run main.go
0
```

匿名函数：

```go
func testDefer() {
    var a, b int
    defer func(){
        fmt.Println(a - b)
    }()
    a, b = 10, 9
}

$ go run main.go
1
```

传递匿名函数时，由于只会拷贝函数的指针，就可以避免参数预计算，比如操作数据库事务时的常用写法：

```go
func deleteArticleFromDB(id int) (err error) {
	tx := DB.Begin()
	defer func() {
		if err != nil {
			tx.Rollback()
		}
		tx.Commit()
	}()
    if err = tx.Where("id = ?", id).Delete(&Article{}).Error; err != nil {
        return err
    }
    if err = tx.Where("article_id = ?", id).Delete(&ArticleTags{}).Error; err != nil {
        return err
    }
	return nil
}
```

## panic 和  recover

`panic()` 和 `recover()` 都是 go 内置的函数，当程序执行到 `panic()`  时，会立刻停止执行当前代码转而去 **递归执行** 调用方延时函数。

```go
func f(){
	defer fmt.Println("f defer")
	fmt.Println("run f")
	panic("panic f")
	fmt.Println("after f panic")
}

func g() {
	defer fmt.Println("g defer")
	fmt.Println("run g")
	f()
	fmt.Println("after call f")
}

func main() {
	g()
}

$ go run main.go
run g
run f
f defer
g defer
panic: panic f

goroutine 1 [running]:
main.f()
        E:/test/main.go:8 +0x102
main.g()
        E:/test/main.go:15 +0xf4
main.main()
        E:/test/main.go:20 +0x27
```

如上，如果不处理 panic, 这个恐慌将会沿着调用链一直传递，直到 `main()`异常退出，而 `recover()` 就是用于恢复由 `panic()` 产生的程序崩溃，类似于 Java 中的 `catch` , `recover()` 只能在 `defer` 中发挥作用。

```go
func f(){
	defer fmt.Println("f defer")
	fmt.Println("run f")
	panic("panic f")
	fmt.Println("after f panic")
}

func g() {
	defer func(){
		if err := recover(); err != nil {
			fmt.Println("recover")
		}
		fmt.Println("g defer")
	}()
	fmt.Println("run g")
	f()
	fmt.Println("after call f")
}

func main() {
	g()
}

$ go run main.go
run g
run f
f defer
recover
g defer
```



