# Go 如何优雅地处理异常

看到脉脉上有人说 Go 语法简洁，下面有人讽刺说 `if err != nil`, 确实简洁，而习惯于 `try-catch-finally` 的我也不止一次吐槽这种奇怪的异常处理方法，直到看到知乎上有个老哥说：“遇到没有 Handle 的异常，让程序停下来是最好的解决办法”，确实，如果遇到的问题是被预料到的，有其对应解决办法的，那就不应该抛出异常，反之，如果出现没有预料到的问题，就应该记录异常信息，并让程序及时停下来，两种情况不应该被混为一谈。

<!-- more -->

而在 Go 的 FAQ 中，也谈到了这个问题：

> ### [Why does Go not have exceptions?](https://golang.org/doc/faq#exceptions)
> We believe that coupling exceptions to a control structure, as in the `try-catch-finally` idiom, results in convoluted code. It also tends to encourage programmers to label too many ordinary errors, such as failing to open a file, as exceptional.
>
> 我们认为，像传统 `try-catch-finally` 那样将异常处理和控制结构相耦合，会使代码变得复杂。并且传统的这种模式还倾向于鼓励程序员将太多数的普通错误(如无法打开文件)标记为异常错误。
>
> Go takes a different approach. For plain error handling, Go's multi-value returns make it easy to report an error without overloading the return value. [A canonical error type, coupled with Go's other features](https://golang.org/doc/articles/error_handling.html), makes error handling pleasant but quite different from that in other languages.
>
> Go 采取了一种截然不同的处理方式，在遇到普通的错误时，可以利用 Go 的多返回值特性在不重载返回值的情况下向调用者报告异常情况，这种方式虽然和其他语言的异常处理有很大不同，但使用规范的错误类型和 Go 的一些其他特性，能让这个过程变得更加有趣。
>
> Go also has a couple of built-in functions to signal and recover from truly exceptional conditions. The recovery mechanism is executed only as part of a function's state being torn down after an error, which is sufficient to handle catastrophe but requires no extra control structures and, when used well, can result in clean error-handling code.
>
> 对于那些真正的异常，Go 也提供了一些机制，使代码从其中恢复，恢复机制仅仅作为发生错误后函数状态被销毁的一部分去执行，这样足够去处理灾难，并且不需要额外的控制结构，如果使用得当，你可以得到更加干净的代码。
>
> See the [Defer, Panic, and Recover](https://golang.org/doc/articles/defer_panic_recover.html) article for details. Also, the [Errors are values](https://blog.golang.org/errors-are-values) blog post describes one approach to handling errors cleanly in Go by demonstrating that, since errors are just values, the full power of Go can be deployed in error handling.
>
> 关于恢复，更多详情请参阅 [Defer, Panic, and Recover](https://golang.org/doc/articles/defer_panic_recover.html)，除此之外，博客 [Errors are values](https://blog.golang.org/errors-are-values) 描述了一种在 Go 中干净利落地处理异常地方法，由于 error 仅仅是一个值，所以 Go 的所有功能都可以被用在错误处理上。

## 区分错误和异常

FAQ 中提到，Go 希望程序员将那些普通的错误和真正的异常区分开来，不要混为一谈，而 Go 的具体做法就是把普通的错误归为 `error`, 这是一个再普通不过的接口，你可以像处理一个其他值一样自由地处理它，而真正的异常，则被称为 `panic`, 运行时错误（数组越界，NPE 等）或调用内置的 `panic()` 函数都会导致程序 “恐慌”，函数一旦发生 “恐慌”，就会立刻停止并执行其延迟调用函数（`defer`）之后，恐慌会沿着函数调用栈一直传递，直到当前 goroutine 中的所有函数全部返回，程序崩溃。

但真正的问题在于如何界定普通错误（error）和真正的异常（panic）呢，引用一句 Go 作者的话：

> When you`panic`in Go, you’re freaking out, it’s not someone elses problem, it’s game over man.

换句话说，那些严重的，不可修复的，需要人工介入的错误应该被定义为 `panic`, 如数组越界，程序初始化时失败等，虽然你可以使用 `recover()` 来恢复它，但这种恢复机制往往被用于高阶的流程控制使得代码更简洁高效（比如在 `fmt` 或 `json` 等包中），毕竟能被恢复的，也就不能称之为 “恐慌” 了。

反之那些可以预测到的，程序可以自己处理的错误就应该被定义为 `error`, 如程序接收到用户的异常输入等……

除此之外，如果你作为服务的提供者，那么暴露出来的接口应该尽量使用 `error` ，毕竟如果使用 `panic`, 那么使用者就需要捕捉你的 `panic`, 而这件事因该由提供者来做，当出现问题时，你只需要明确地通知使用者出现了什么问题，而至于如何处理该问题，则由使用者决定。

## 如何更好地处理错误

`panic` 只在程序出现严重错误时出现，而在这个时候我们能真正做的事其实并不多（当然，用 panic 配合 recover 做更高级的操作除外），所以，如何更好地处理 `error` 应该更值得我们讨论（这里也是大家吐槽 go 的重灾区，毕竟我还没见过有人吐槽 Go 的 panic......）。

### error 是什么

`error` 是定义在 builtin 中的一个接口，该接口只有一个待实现的方法 `func Error() string`，他向调用者返回一段提示已告知其发生了什么错误：

```go
type error interface {
	Error() string
}
```

任何实现了该方法的结构都可以作为 `error`, 如：

```go
type FileNotFindException struct {
    path string
}

func (f *FileNotFindException) Error() string {
    return f.path + "not find"
}

func open(path string) error {
    return &FileNotFindException{path: path}
}
```

而在实际使用中，我们可以使用官方的`errors` 包中的 `New()` 快速生成这样一个简单的 `error`:

```go
package errors

func New(text string) error {
	return &errorString{text}
}

type errorString struct {
	s string
}

func (e *errorString) Error() string {
	return e.s
}
```

除了 `New()`, errors 包中还提供了三个很方便的功能：`Unwrap()`, `Is()`, `As()` 这三个函数在 Go 1.13 时被加入，与之同时加入的还有 `fmt.Errorf()`.

`fmt.Errorf()` 也可以用来构造一个 `error`， 与 `New()` 不同之处在于 `Errorf()` 支持一个 `%w` 字面量，通过此，你可以将一个 `error`  包装成一个新的 `error`, 就像下面这样：

```go
func readFile() error {
    err := open("xx")
    return fmt.Errorf("%w fail to read", err)
}
```

在内部，Errorf 会根据有没有 `%w` 决定是使用 `errors.New()` 创造一个普通的 `error` 还是创造一个包装后的 `wrapError`:

```go
type wrapError struct {
	msg string
	err error
}

func (e *wrapError) Error() string {
	return e.msg
}

func (e *wrapError) Unwrap() error {
	return e.err
}
```

`wrapError` 中:

* msg 是两个 error 的 msg 拼接后的结果，如上面的例子， msg 就是 `xx not find fail to read`
* err 保存了旧的 error, 如上面的例子中， err 就是 open 返回的 FileNotFindException

对错误进行包装后，可以调用 `errors.Unwrap()`  得到包装前的错误，`errors.Unwrap()` 的实现很简单，如果一个 error 类型实现了 `Unwrap()` 方法，就返回带方法执行后的结构，否则返回 nil:

```go
func Unwrap(err error) error {
	u, ok := err.(interface {
		Unwrap() error
	})
	if !ok {
		return nil
	}
	return u.Unwrap()
}
```

`errors.Unwrap()` 会返回装饰前的 error, 并不修改原来的 error, 如果你需要将一个 error 回退到装饰前的某一个版本，可以使用 `errors.As()`:

```go
func As(err error, target interface{}) bool {
	if target == nil {
		panic("errors: target cannot be nil")
	}
	val := reflectlite.ValueOf(target)
	typ := val.Type()
	if typ.Kind() != reflectlite.Ptr || val.IsNil() {
		panic("errors: target must be a non-nil pointer")
	}
	if e := typ.Elem(); e.Kind() != reflectlite.Interface && !e.Implements(errorType) {
		panic("errors: *target must be interface or implement error")
	}
	targetType := typ.Elem()
	for err != nil {
		if reflectlite.TypeOf(err).AssignableTo(targetType) {
			val.Elem().Set(reflectlite.ValueOf(err))
			return true
		}
        // 如果 err 实现了 As 方法，就执行其 As 方法
		if x, ok := err.(interface{ As(interface{}) bool }); ok && x.As(target) {
			return true
		}
		err = Unwrap(err)
	}
	return false
}
```

如果想要判断一个 error 是不是由另一个 error 包装而来的，可以使用 `errors.Is()`:

```go
if target == nil {
		return err == target
	}

	isComparable := reflectlite.TypeOf(target).Comparable()
	for {
		if isComparable && err == target {
			return true
		}
		if x, ok := err.(interface{ Is(error) bool }); ok && x.Is(target) {
			return true
		}
		if err = Unwrap(err); err == nil {
			return false
		}
	}
```

通过这四个函数，error 可以被组织成一个有层次的链，方便开发和处理。

如果你还需要一些功能，比如记录错误的栈信息等，可以使用 `github.com/pkg/errors` 他与官方的 `errors` 完全兼容，它提供了一些很实用的方法：

* `New()`: 类似于 `errors.New()`, 不过在此基础上添加了错误栈信息
* `Errorf()`: 类似于 `fmt.Errorf()` 不使用 `%w` 的情况, 添加了错误栈信息
* `WithStack()`: 为一个 error 添加错误栈信息
* `Wrap(error, string)`: 将一个 error 包装为一个新 error
* `Wrapf(error, string, ...interface{})`: 类似于 `Wrap()`
* `WithMessage(error, string)`: 类似于 `fmt.Errorf()` 使用 `%w` 的情况，使用一段新的 msg 包装 error, 与 `Wrap()` 不同在于它不会添加栈信息。
* `WithMessagef(error, string, ...interface{})`: 类似于 `WithMessage()`
* `WithStack(error)`: 为 error 添加错误栈信息
* `Cause(error) error` 返回 error 产生的根本原因（一直剥离到最后一层）
* `Is()`: 同 `errors.Is()`
* `As()`: 同 `errors.As()`
* `Unwrap()`: 同 `errors.Unwrap()`

### 能不能少写点代码











